<?php
        $url="";
        if(array_key_exists('url', $_GET)){
            $url = $_GET['url']; 
            // explicitly cast value to an integer
        }

	   if($url!=""){
            // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
            $ch = curl_init();
            
            curl_setopt($ch, CURLOPT_URL, 'https://api.remove.bg/v1.0/removebg');
            curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
            curl_setopt($ch, CURLOPT_POST, 1);
            $post = array(
                'image_url' => $url,
                'size' => 'auto'
            );
            curl_setopt($ch, CURLOPT_POSTFIELDS, $post);
            
            $headers = array();
            $headers[] = 'X-Api-Key: uZqwe9zhJs5Z4YmpokkR3g5k ';
            curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
            
            $result = curl_exec($ch);
            if (curl_errno($ch)) {
                echo 'Error:' . curl_error($ch);
            }
            curl_close($ch);
            
            $fp=fopen('src/img/output.png',"wb");
            fwrite($fp,$result);
            fclose($fp);
        }
	
	?>